# Generated by Django 2.1.2 on 2018-10-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0002_auto_20181020_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perros_rescatados',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='perros_rescatados',
            name='published_date',
        ),
    ]
