# Generated by Django 2.1.2 on 2018-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0006_auto_20181020_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_field',
            field=models.CharField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=100),
        ),
    ]
