# Generated by Django 2.1.2 on 2018-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0007_auto_20181020_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_field',
            field=models.CharField(choices=[('item_key1', 'Rescatado'), ('item_key2', 'Disponible'), ('item_key3', 'Adoptado')], max_length=100),
        ),
    ]
