# Generated by Django 2.1.2 on 2018-10-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0010_auto_20181020_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
