# Generated by Django 2.1.2 on 2018-10-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0011_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='perros_rescatados',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
